services:
  rcs-api:
    build: .
    container_name: rcs_backend
    ports:
      - "5050:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app          # Monta tu código fuente local en el contenedor
      
    command: >
      sh -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
      sleep 3 &&
      ngrok config add-authtoken $NGROK_AUTHTOKEN &&
      ngrok http 8000"
    restart: always